---
galaxy_info:
  author: prutledg
  description: Common tasks for Lenovo XClarity BMC management via Redfish API
  company: 
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  
  galaxy_tags:
    - redfish
    - bmc
    - lenovo
    - xclarity
    - server
    - management

dependencies: [] 